### ISSUE TITLE
Make player attack based on user input

### ISSUE THREAD

**Issue by brenthaertlein** [nodemules/SuperPlatformerBros#10]
* animation
* sound
* conditionally enabled trigger

Time the "swing" of the player's weapon (Marsh's Torch) with an animation, a sound, and a window of time where the existing trigger (probably make it larger) becomes enabled for killing enemies

**Comment by staticsound** [comment]
Basic concept (animation, sound, conditional trigger) in place- tweaks for box collider size/position and animation need to be made.

**Comment by staticsound** [comment]
Done
