### ISSUE TITLE
Display # of Lives in UI

### ISSUE THREAD

**Issue by brenthaertlein** [nodemules/SuperPlatformerBros#13]
Make a UI element showing the current number of player lives

**Comment by brenthaertlein** [comment]
Idea: Show X Marsh(s) in the top left

**Comment by brenthaertlein** [comment]
When showing 5 or more (_25 or more_) use Marsh `x 5`

**Comment by staticsound** [comment]
For simplicity we have opted to just show the number value next to an icon. Can revisit later if we need to.
