### ISSUE TITLE
Gain extra life from coins

### ISSUE THREAD

**Issue by brenthaertlein** [nodemules/SuperPlatformerBros#14]
When X coins are collected, gain a life

**Comment by brenthaertlein** [comment]
`X=10`?

**Comment by brenthaertlein** [comment]
We should consider this when we're playtesting... is the game impossible at 3 lives? Is it too hard entirely? What is the right number of coins to gain a life? 10 is a nice number but probably too low.

**Comment by staticsound** [comment]
Basic implementation. Can go back and improve what we are doing for the "font changing effect" for both coins and lives if we want. Currently set to 10 coins for an extra life. 

Would not hurt to add a sound effect
