### ISSUE TITLE
Title screen

### ISSUE THREAD

**Issue by brenthaertlein** [nodemules/SuperPlatformerBros#16]
~~Add a title screen with START and QUIT~~

Add a title screen with PRESS JUMP TO START

**Comment by staticsound** [comment]
Name Idea: "Marsh's Mellow Adventure"

or "Marsh's Mellow Odyssey: Not Your Typical MMO as it's not Multiplayer nor Online"

**Comment by brenthaertlein** [comment]
Moved the QUIT functionality to #30

**Comment by brenthaertlein** [comment]
`b052c4b8f3153097382895e375cc62d4c170b0e0` and `bcf2857fd6e285c2c6ffb5133d6a05c9fcce0945`
