### ISSUE TITLE
Fix Death Sound

### ISSUE THREAD

**Issue by staticsound** [nodemules/SuperPlatformerBros#19]
Death sound currently just plays when the game over screen is loaded. Change this to play when player dies. Don't play sound or play different sound when it's a game over.

**Comment by brenthaertlein** [comment]
Play a different sound for game over vs player death

Stop background music when playing player death sound

**Comment by brenthaertlein** [comment]
I think we just play a death sound (needle scratch) with stopping the music, and then game over music. We don't need a game over sound

**Comment by staticsound** [comment]
Went with the proposed solution above
