### ISSUE TITLE
Make an Animation and Delay For Death

### ISSUE THREAD

**Issue by staticsound** [nodemules/SuperPlatformerBros#21]
Right now when Marsh dies it immediately starts you back which sounds/looks a bit jarring. He already turns on his side so that could act as the animation but we should perhaps delay the restart by 1 second and add a sound. I like the record needle scratch for the true death though, we should probably keep that is and make a slightly less intense sound for each death.

**Comment by brenthaertlein** [comment]
I think this probably covers #19 as well
