### ISSUE TITLE
Design a way to defeat boss blobs

### ISSUE THREAD

**Issue by brenthaertlein** [nodemules/SuperPlatformerBros#27]
~~Make it so that boss blobs cannot be defeated with Marsh's Torch~~

Design a [clever](https://media.giphy.com/media/11oppolhqgE8M0/giphy.gif) way to defeat the boss blobs

**Comment by staticsound** [comment]
At the very least the block to win should not appear until you've killed all 3 of them.

**Comment by brenthaertlein** [comment]
pretty good boss killin going on
