### ISSUE TITLE
Jumping doesnt work in build

### ISSUE THREAD

**Issue by brenthaertlein** [nodemules/SuperPlatformerBros#31]
Marsh cannot jump in a MacOS build.

The jump sound plays, but the character does not jump.

Check Windows build for how this functionality behaves

**Comment by staticsound** [comment]
Changing this to just "build" as I created a windows build and it does not work there either. 

Investigate `GetButton` vs `GetButtonDown` and other things.

**Comment by staticsound** [comment]
I tried most things from this guy's list to no avail: https://forum.unity.com/threads/script-not-working-in-build-ok-in-editor.40806/

**Comment by staticsound** [comment]
Get this error in logs of build but not in play mode:
```
NullReferenceException: Object reference not set to an instance of an object
  at Assets.Scripts.CameraSystem.LateUpdate () [0x00007] in /Users/charles/Code/SuperPlatformerBros/Assets/Scripts/CameraSystem.cs:32 
 
(Filename: /Users/charles/Code/SuperPlatformerBros/Assets/Scripts/CameraSystem.cs Line: 32)
```

**Comment by staticsound** [comment]
Fixed. Gravity Changed.
