### ISSUE TITLE
provide ability to toggle triggered effects with block

### ISSUE THREAD

**Issue by staticsound** [nodemules/SuperPlatformerBros#42]
Right now the trigger blocks can make an event happen once but not toggle it. Provide both options.

**Comment by brenthaertlein** [comment]
This functionality is already supported by allow triggers to fire multiple times, however there is no implementation for unlimited uses (just a very large number, probably `MAX_INTEGER`).

I think this ticket should be used for fleshing this functionality out per our conversation.

Some of the feature improvements we talked about were:

* Triggers can be fired unlimitedly, or respect a max fire count on the Trigger object side
* Triggereables can be fired unlimitedly or respect a max fire count on the Triggerable object side
* A container or some other element for firing multiple Triggerables from a single Trigger, or a way to include multiple triggers on the Trigger component UI

**Comment by brenthaertlein** [comment]
https://answers.unity.com/questions/192895/hideshow-properties-dynamically-in-inspector.html

Make an issue that considers using this concept for when `IsToggle` is set by the editor thingy

**Comment by brenthaertlein** [comment]
*Done* _Triggers can be fired unlimitedly, or respect a max fire count on the Trigger object side_

Additionally, `HideableContainer` can start in a `Show` state where all the child GameObjects are shown instead of hidden by default.

**Comment by brenthaertlein** [comment]
_A container or some other element for firing multiple Triggerables from a single Trigger, or a way to include multiple triggers on the Trigger component UI_ will allow having one trigger toggle off multiple HideableContainers to emulate the effect that is lost by forcing all of the IHideable children to be explicitly hidden or shown with the changes in [ea75ed1](https://github.com/nodemules/SuperPlatformerBros/commit/ea75ed13e39d488ac31b491772b553bc7259a5e3)

**Comment by brenthaertlein** [comment]
Closing because the spirit of this issue is complete, moved the multi-trigger functionality to a new ticket.
