### ISSUE TITLE
Improve Marsh animations

### ISSUE THREAD

**Issue by brenthaertlein** [nodemules/SuperPlatformerBros#50]
When walking or jumping, use the current full cycle of animations.

When Marsh is standing still, use less animation frames so there is a distinction between movement and not moving.

**Comment by staticsound** [comment]
There is now a still animation and a walking animation that does the above. I noticed when Marsh attacks while standing still it now looks a little lackluster- I've added an attack animation as well but implementation hasn't happened yet. The path I went down I wasn't thrilled about so I want to think about it a bit. 

Right now the animation is based on movement, which is based on `Update()` which I'm not in love with either as it makes additional animations challenging. But I also don't want to have a series of _isDoingTheThing = !_isDoingTheThing everywhere.
