### ISSUE TITLE
Winning Music

### ISSUE THREAD

**Issue by brenthaertlein** [nodemules/SuperPlatformerBros#8]
Play `Charlie Sheen - Blood of the Tiger.mp3` when the player finished the last level

**Comment by staticsound** [comment]
We need to handle music programmatically because winning and gameover screens are part of the same scene.

**Comment by staticsound** [comment]
Added conditional logic to play the right music based on game over vs. winning screen. Right now I put the winning music as the title screen music- can change later if desired but I'm going to close this.
